### ISSUE TITLE
install vim in the vagrant box

### ISSUE THREAD

**Issue by emmanuelbernard** [debezium/microservices-lab#31]
What are you people? Animals!?

**Comment by emmanuelbernard** [comment]
It will be useful to check the template files and all the other files we inject into the oc commands. If we want people to understand anything, we will need to show them.

**Comment by gunnarmorling** [comment]
@jpechane Can you add it? Although I actually thought it's there already.

**Comment by jpechane** [comment]
Command is `vi` not `vim`

**Comment by gunnarmorling** [comment]
Closing; please use `vi` as every normal animal on this planet ;)
