### ISSUE TITLE
Scaling to 5 Kafka nodes failed due to insufficient memory

### ISSUE THREAD

**Issue by emmanuelbernard** [debezium/microservices-lab#36]
10:39:27 AM | Warning | Failed Scheduling | 0/1 nodes are available: 1 Insufficient memory.25 times in the last

Gunnar recommends to scale down to 1 instead of up.
Scaling up to 4 nodes was fine so we can try 4 and then ask to move down to 1 at the end of module 1

**Comment by emmanuelbernard** [comment]
I'll be trying the lab with 3 nodes though

**Comment by jpechane** [comment]
Removed https://github.com/debezium/microservices-lab/pull/51
