### ISSUE TITLE
Email to attendees

### ISSUE THREAD

**Issue by emmanuelbernard** [debezium/microservices-lab#54]
Title: Installs required on your laptop to attend the Boundaries of Microservices workshop

Hi everyone,

We are excited to work with you during the Voxxed workshop!
There is a few things you must install on your laptop to effectively follow the workshop.

* Java 1.8
* Maven (latest ideally)
* your favorite IDE (vim forever! but really whatever Java IDE you are comfortable with)
* VirtualBox 5.2 https://www.virtualbox.org/
* Vagrant 2.x https://www.vagrantup.com/
* Get a GitHub account http://github.com/

We will run a VM using 2 vCPU and 6GB of RAM. Make sure you have enough.

With that install, you should be ready to run!
Next week, we will give you instruction to pre-download the VM image, we are still tweaking it a bit as we speak. **Please make sure to download this image before coming to the workshop as the image will be ~3GB.**

Thanks and see you Wednesday!

Linda, Régina, Gunnar and Emmanuel

**Comment by gunnarmorling** [comment]
> Next week, we will give you instruction to pre-download the VM image, we are still tweaking it a bit as we speak.

Let's say

> Early next week, we will give you instruction to pre-download the VM image, we are still tweaking it a bit as we speak. Please make sure to download this image before coming to the workshop.
