### ISSUE TITLE
Scaling to one Kafka node breaks module 2

### ISSUE THREAD

**Issue by gunnarmorling** [debezium/microservices-lab#56]
@jpechane That's my biggest concern at this point. It'd be nice to work with a single node, but it seems the topic has no leader then for some reason.

**Comment by gunnarmorling** [comment]
Hum, so it seems to be only an issue with the console consumer, as the invoice application receives the messages.

**Comment by jpechane** [comment]
Solved - the bootstrap server should be `localhost:9092`

**Comment by gunnarmorling** [comment]
Interesting; why is that, though? I.e. why does it work with `--bootstrap-server my-cluster-kafka-bootstrap:9092` if there are three nodes but not if there's just one?

**Comment by gunnarmorling** [comment]
I had created https://github.com/strimzi/strimzi-kafka-operator/issues/1034 upstream, perhaps at least some doc update might be warranted.

**Comment by gunnarmorling** [comment]
So it's a known problem; as per @ppatierno, "[if there's a single node], it's a problem of the routing service in OpenShift. It happens that it's not able to redirect the traffic to itself."

I've adjusted the instructions to use localhost if the cluster has been scaled down to a single node.
