### ISSUE TITLE
Shoudl we use Postgres? Maybe PostgreSQL is more appropriate

### ISSUE THREAD

**Issue by jpechane** [debezium/microservices-lab#69]

**Comment by gunnarmorling** [comment]
What's the argument for it? In fact I like the story of propagating changes across vendors. It's a clear advantage of DBZ/CDC over using the DB's built-in replication tools.

**Comment by jpechane** [comment]
I mean only brand :-) So instead of using Postgres use the full PostgreSQL as the materials are somewhat official

**Comment by gunnarmorling** [comment]
Aaaah, ok :) I thought you meant to change the underlying source DB. Yes, just change it, please.

**Comment by jpechane** [comment]
https://github.com/debezium/microservices-lab/pull/70

**Comment by gunnarmorling** [comment]
Done.
