### ISSUE TITLE
Docs Issue For Kafka Console Consumer

### ISSUE THREAD

**Issue by sherl0cks** [debezium/microservices-lab#72]
https://github.com/debezium/microservices-lab/blame/master/voxxed-microservices-2018/module-02.adoc#L198 should be `--topic orders` instead of `--topic myorders`

**Comment by sherl0cks** [comment]
Looks like this issue propagates elsewhere. Instead of updating the docs, we could update the order service to set an env var on the deployment for the topic name. Which would you prefer?

**Comment by gunnarmorling** [comment]
Hi @sherl0cks,  sorry, I totally missed this one. It's obsolete by now, as the topic has been globally renamed everywhere. Thanks for giving the lab a try!
